### ISSUE TITLE
The resultant APK is timestamped as 1981

### ISSUE THREAD

**Issue by slavdok** [MartinGonzalez/fastlane-plugin-bundletool#10]
Version: fastlane-plugin-bundletool (1.0.6)

![image](https://user-images.githubusercontent.com/54748546/218380235-cd2d3abd-98e4-4158-9680-26e63f7c585e.png)

On MacOS Monterey (have not tested other OSes), the resultant APK is timestamped in the year 1981

**Comment by MartinGonzalez** [comment]
Indeed, it does that, seems to be a bug from bundletool since i'm just unzipping the apk.
I have created a bug report on bundletool repo if you are interested: https://github.com/google/bundletool/issues/316

**Comment by MartinGonzalez** [comment]
So seems that they are doing this on purpose, so I think we can understand that is not an issue, and also is not related with this plugin :)

https://github.com/google/bundletool/issues/316#issuecomment-1672310543
