### ISSUE TITLE
Cache bundletool 

### ISSUE THREAD

**Issue by BANG88** [MartinGonzalez/fastlane-plugin-bundletool#12]
https://github.com/MartinGonzalez/fastlane-plugin-bundletool/blob/master/lib/fastlane/plugin/bundletool/actions/bundletool_action.rb#L47

Hi, @MartinGonzalez Could we don't download the bundle tool at every run? we should download it once and cache it.

Thank you.

**Comment by Martin-Gonzalez90** [comment]
Hi @BANG88 !
Looks like a very good improvement. I will try to do it these days! 💪

**Comment by BANG88** [comment]
Thank you for your quick response. I am waiting online.  👍

**Comment by MartinGonzalez** [comment]
Hi! An update of this!
Soon will be released

https://github.com/MartinGonzalez/fastlane-plugin-bundletool/pull/13

**Comment by MartinGonzalez** [comment]
Released! [fastlane-plugin-bundletool (1.0.8)](https://rubygems.org/gems/fastlane-plugin-bundletool/versions/1.0.8)
Thanks for the feature request! I will close this issue, if you have any other comment you can still use this or create a new one :)

**Comment by BANG88** [comment]
Thanks
