### ISSUE TITLE
Please add the tag for version 1.0.5

### ISSUE THREAD

**Issue by sschuberth** [MartinGonzalez/fastlane-plugin-bundletool#8]
That would make it easier to match the source code for that version.

**Comment by sschuberth** [comment]
I guess the tag should point to commit ec68629be155b2c659bdff6d582e2b36a1c2efed (guessed from the [date in the changelog](https://github.com/MartinGonzalez/fastlane-plugin-bundletool/blob/master/CHANGELOG.md#105---2022-02-11))?

**Comment by MartinGonzalez** [comment]
@sschuberth Thanks for pointing that. Tag [1.0.5](https://github.com/MartinGonzalez/fastlane-plugin-bundletool/releases/tag/1.0.5) was created.

Feel free to add any other request or close the issue :)

**Comment by sschuberth** [comment]
Thanks for the fast action!
