### ISSUE TITLE
Unless verbose is set to true, the plugin does nothing

### ISSUE THREAD

**Issue by slavdok** [MartinGonzalez/fastlane-plugin-bundletool#9]
Version: fastlane-plugin-bundletool (1.0.6)

If "verbose" is set to false, or omitted, the tool does literally nothing.
It displays params summary, but no action is performed, no files are created.

**Comment by MartinGonzalez** [comment]
Hi! Thanks for reporting it!
Will check this during the day and will come back with more info 💪

**Comment by MartinGonzalez** [comment]
Merged and release in version 1.0.7 🚀 
Thanks for reporting!

Feel free to close whenever you want
